create table if not exists public.agent_answers (
  id bigint generated by default as identity primary key,
  query_id bigint not null references public.agent_queries(id) on delete cascade,
  answer_text text not null check (char_length(trim(answer_text)) > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists agent_answers_query_id_uniq
  on public.agent_answers (query_id);

create index if not exists agent_answers_created_idx
  on public.agent_answers (created_at desc);

alter table public.agent_answers enable row level security;

drop policy if exists "agent_answers_select_own" on public.agent_answers;

create policy "agent_answers_select_own"
on public.agent_answers
for select
to authenticated
using (
  exists (
    select 1
    from public.agent_queries aq
    where aq.id = agent_answers.query_id
      and aq.user_id = auth.uid()
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'agent_answers'
  ) then
    alter publication supabase_realtime add table public.agent_answers;
  end if;
end
$$;
