create table if not exists public.agent_queries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  question text not null check (char_length(trim(question)) > 0),
  agent_type text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'done', 'failed')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists agent_queries_user_created_idx
  on public.agent_queries (user_id, created_at desc);

alter table public.agent_queries enable row level security;

drop policy if exists "agent_queries_select_own" on public.agent_queries;
drop policy if exists "agent_queries_insert_own" on public.agent_queries;
drop policy if exists "agent_queries_update_own" on public.agent_queries;

create policy "agent_queries_select_own"
on public.agent_queries
for select
to authenticated
using (auth.uid() = user_id);

create policy "agent_queries_insert_own"
on public.agent_queries
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "agent_queries_update_own"
on public.agent_queries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

alter publication supabase_realtime add table public.agent_queries;
